### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by Applemann** [way-cooler/way-cooler#334]
Hello I have another problem.. :)
After successful build I installed: way-cooler-bg  wc-grab  wc-lock
via some part of this script:  https://way-cooler.github.io/way-cooler-release-i3-default.sh
and run way-cooler.
It was started, but I got this output:

```
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:191 Lua: awaiting request
thread 'main' panicked at 'Could not talk to Way Cooler -- is Way Cooler running?: D-Bus error: The name org.way-cooler was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x561f71073dcc - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x561f71076cbe - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x561f710768c4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x561f7107715b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x561f71076ff4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x561f71076f19 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x561f71076ea7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x561f7109efdd - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x561f70f27e28 - core::result::unwrap_failed::h2ed6b20536231858
  10:     0x561f70f2ea44 - way_cooler_bg::get_screen_resolution::h0c36067ed0415487
  11:     0x561f70f2b08b - way_cooler_bg::main::h16eae7f9bfaedf81
  12:     0x561f7107e01a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  13:     0x561f710778c6 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  14:     0x7f7b457eb82f - __libc_start_main
  15:     0x561f70f272b9 - _start
  16:                0x0 - <unknown>
             at /checkout/src/libcore/macros.rs:29
  10: way_cooler::ipc::session::DBusSession::create
             at /checkout/src/libcore/result.rs:761
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/ipc/session.rs:26
  11: std::panicking::try::do_call
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/ipc/mod.rs:34
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
  14: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  15: start_thread
  16: clone

```

**Comment by Timidger** [comment]
Try `dbus-launch --exit-with-session way-cooler` when launching Way Cooler

**Comment by Applemann** [comment]
@Timidger ok now I have this: 

```
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:348 Updating programs:x11_bar = String(
    "lemonbar"
)
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:348 Updating programs:lock_screen = String(
    "wc-lock"
)
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:348 Updating mouse:lock_to_corner_on_resize = Boolean(
    false
)
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:191 Lua: awaiting request
 TRACE [callbacks] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/callbacks.rs:67 view_props_changed for view WlcView { handle: 2, title: "", class: "Background" }: PROPERTY_APP_ID
 ERROR [modes::default] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/modes/default.rs:179 Could not update title for view WlcView { handle: 2, title: "", class: "Background" } because ViewNotFound(
    WlcView {
        handle: 2,
        title: "",
        class: "Background"
    }
)
 TRACE [callbacks] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/callbacks.rs:67 view_props_changed for view WlcView { handle: 2, title: "Background Color: 102197331", class: "Background" }: PROPRETY_CLASS
 ERROR [modes::default] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/modes/default.rs:179 Could not update title for view WlcView { handle: 2, title: "Background Color: 102197331", class: "Background" } because ViewNotFound(
    WlcView {
        handle: 2,
        title: "Background Color: 102197331",
        class: "Background"
    }
)
 TRACE [callbacks] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/callbacks.rs:49 view_created: WlcView { handle: 2, title: "Background Color: 102197331", class: "Background" }: "Background Color: 102197331"
 TRACE [modes::default] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/modes/default.rs:105 Setting background: Background Color: 102197331

```

**Comment by Timidger** [comment]
Ok it looks like it's authenticating properly, and the background is attaching to it. If you didn't modify the default configuration, you should have a purple background on your main output. 

The error about updating the title is a misnomer. 

The lock screen program and screen capture are programs that should be spawned be the user (either via a keybinding you bind to spawn it, or manually using dmenu or a terminal). Is there some issue with the that I'm not seeing?

**Comment by Applemann** [comment]
@Timidger No there is only problem with the Background error
Do you know how can I fix it??

**Comment by Timidger** [comment]
Is it only an error in the log? Eg does the background display or not? If it does display you can happily ignore the "error". It shouldn't be causing Way Cooler to panic (ie crash). If it does, let me know and include a full log.

**Comment by Applemann** [comment]
@Timidger No way-cooler doesn't work.
I am trying it in virtual box and when I run command: `dbus-launch --exit-with-session way-cooler`
And I see this: 
![way-cooler-error](https://user-images.githubusercontent.com/2686906/28241886-2513748a-699e-11e7-858e-3248d820464f.png)

Only black background and arrow. (I can't to do anything..)
Here is the full log: https://pastebin.com/JgHhwR0C

**Comment by Timidger** [comment]
If you're running in virtual box, please ensure that it's allowing your key presses to go through. Looking at the logs, it's defaulting to the pre-compiled init file (since you don't have one in your virtualbox session). By default, we use "alt" as the meta key to do an action, e.g "alt+enter" will spawn a terminal (defaults to `weston-terminal`, which will obviously fail if you don't have that installed) and "alt+d" will spawn `dmenu` (again, assuming you have it installed).

By googling around, [it looks like virtualbox doesn't pass through the alt key](https://superuser.com/questions/710091/how-to-use-the-alt-key-in-a-virtual-box-guest-session). Try allowing it to pass through, or download the [init.lua file](https://github.com/way-cooler/way-cooler/blob/master/config/init.lua) from the repo and change the meta key to something that will pass through (e.g "Ctrl"). If you go with the second option, put the configuration file in `~/.config/way-cooler/init.lua`.

**Comment by Applemann** [comment]
@Timidger ok I tryed run: `Alt+Enter`
and I got:
```
 INFO [modes::default] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/modes/default.rs:251 [key] Found an action for Keypress(MOD_ALT, Some("Return")), blocking event
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:202 Handling a request
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:287 Lua: handling keypress Keypress(MOD_ALT, Some("Return"))
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:297 Handled keypress okay.
 TRACE [lua::thread] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.0/src/lua/thread.rs:191 Lua: awaiting request
weston-terminal: clients/window.c:5077: window_create_internal: Assertion `custom || display->xdg_shell || display->ivi_application' failed.
```

and weston-terminal I have installed.

Shortcut for exit way-cooler: `Alt+Shift+Escape` works fine.

And I am also trying move mouse in vitrualbox, but doesn't work..

**Comment by Timidger** [comment]
Sounds like the xdg shell versions don't line up properly. Can you post the output of `ls -l /usr/share/wayland-protocols/unstable/xdg-shell/`? We (half) support v6, and you'll need that to use Way Cooler properly. Older versions of Way Cooler supported v5. It's potentially possible to run the current version with an old version of xdg_shell, but you'd have to downgrade your wlc version to before they changed it (and I'm pretty sure that version would be ABI-incompatible, since there have been quite a few changes since then). If you don't have v6, I suggest using your package manager + google to find out how to get v6 on your machine.

Assuming you have xwayland installed, you can launch other applications with `dmenu` ("alt+d") and see if those work. You can also change your default terminal emulator if you follow the steps I outlined in my previous comment and add a custom `init.lua` to `~/.config/way-cooler/`.

**Comment by Applemann** [comment]
@Timidger  Hello so I installed Way-cooler on my pc with your fixed installation script: https://github.com/way-cooler/way-cooler/issues/326#issuecomment-318848444
And now it starts fine. :)

Xdg-shell I would like replace by gnome-terminal if is it possible..
For another problems with applications in way-cooler I opened new issue: https://github.com/way-cooler/way-cooler/issues/357 ;)
