### ISSUE TITLE
Segmentation fault running without xwayland installed

### ISSUE THREAD

**Issue by Xenopathic** [way-cooler/way-cooler#411]
I tried running way-cooler within X (specifically within i3), and it segfaulted after flashing up a window with the following backtrace:

```
#0  0x00007ffff5d2f137 in wl_list_remove () at /usr/lib/libwayland-server.so.0
#1  0x00007ffff7bb8e99 in  () at /usr/lib/libwlc.so.0
#2  0x00007ffff7b9aa47 in  () at /usr/lib/libwlc.so.0
#3  0x00007ffff7bb652c in  () at /usr/lib/libwlc.so.0
#4  0x00007ffff7bb6de6 in  () at /usr/lib/libwlc.so.0
#5  0x00007ffff5d2ab82 in  () at /usr/lib/libwayland-server.so.0
#6  0x00007ffff5d2ace1 in wl_client_destroy () at /usr/lib/libwayland-server.so.0
#7  0x00007ffff5d2adb9 in  () at /usr/lib/libwayland-server.so.0
#8  0x00007ffff5d2c9b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007ffff5d2b14c in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x00007ffff7bb3f4d in wlc_run () at /usr/lib/libwlc.so.0
#11 0x00005555558bcd69 in rustwlc::run_wlc () at /home/users/robin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustwlc-0.6.3/src/lib.rs:235
#12 0x00005555558960b8 in way_cooler::main () at src/main.rs:216
```

A bit of pot luck led me to install xwayland, and that fixed the segfault. This should really be a more sensible error message though, rather than a segfault!

**Comment by alexander-smoktal** [comment]
@Xenopathic, this is a wlc issue. They've fixed it recently

**Comment by Timidger** [comment]
Thanks for the bug report, at @alexander-smoktal pointed out this is a wlc issue. We will be switching to wlroots in the future, so if the issue persists to then feel free to open another issue.
